import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Create admin user
  const hashedPassword = await bcrypt.hash('password123', 10);
  
  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      password: hashedPassword,
      role: 'ADMIN',
      profile: {
        create: {
          firstName: 'Admin',
          lastName: 'User',
          mbtiCompleted: true,
          mbtiType: 'ENTJ',
        },
      },
    },
  });

  // Create regular user
  await prisma.user.upsert({
    where: { email: 'user@example.com' },
    update: {},
    create: {
      email: 'user@example.com',
      password: hashedPassword,
      role: 'STUDENT',
      profile: {
        create: {
          firstName: 'Regular',
          lastName: 'User',
          mbtiCompleted: false,
        },
      },
    },
  });

  // Helper function to generate a random future date for deadlines
  const generateFutureDate = () => {
    const today = new Date();
    // Random number of days between 30 and 90
    const daysToAdd = Math.floor(Math.random() * (90 - 30 + 1)) + 30;
    const futureDate = new Date(today);
    futureDate.setDate(today.getDate() + daysToAdd);
    return futureDate;
  };

  // Create sample job postings
  const jobPostings = [
    {
      title: 'Arabic Language Instructor',
      company: 'Global Islamic Academy',
      location: 'Penang',
      salary: 'RM 3,500 - RM 5,000',
      description: 'Teach Arabic language courses to students of all levels. Create curriculum and assess student progress.',
      requirements: 'Bachelor\'s degree in Arabic Language or related field. Minimum 2 years teaching experience.',
      responsibilities: 'Develop and deliver Arabic language curriculum\nConduct classes for various proficiency levels\nAssess student performance and provide constructive feedback\nPrepare teaching materials and resources\nOrganize cultural events to enhance language learning\nMaintain accurate records of student attendance and progress',
      benefits: 'Medical and dental coverage\nAnnual performance bonus\nProfessional development opportunities\nSubsidized housing\nPaid annual leave\nFlexible working hours',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFJ,INFJ,ENFP,INFP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Islamic Studies Lecturer',
      company: 'Madrasah Al-Hikmah',
      location: 'Selangor',
      salary: 'RM 4,500 - RM 6,000',
      description: 'Conduct lectures on various Islamic topics. Guide students in their research and academic development.',
      requirements: 'Master\'s degree in Islamic Studies or related field. Strong knowledge of Islamic jurisprudence.',
      responsibilities: 'Deliver engaging lectures on Islamic theology, history, and jurisprudence\nDevelop course materials and assessment methods\nSupervise student research projects and dissertations\nContribute to curriculum development\nParticipate in academic committees and departmental activities\nPublish research in relevant Islamic studies journals',
      benefits: 'Comprehensive health insurance\nResearch funding opportunities\nSubsidized campus housing\nRetirement savings plan\nPaid sabbatical leave\nRelocation assistance',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,ISTJ,INFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Quran Teacher',
      company: 'Islamic Learning Center',
      location: 'Kuala Lumpur',
      salary: 'RM 3,000 - RM 4,500',
      description: 'Teach Quran recitation and memorization techniques. Provide personalized attention to students.',
      requirements: 'Ijazah in Quran recitation. Experience teaching children and adults.',
      responsibilities: 'Teach Quran recitation with proper Tajweed rules\nFacilitate Quran memorization sessions\nConduct one-on-one student assessments\nProvide customized learning plans for each student\nOrganize Quran competitions and events\nMaintain regular communication with parents/guardians',
      benefits: 'Healthcare allowance\nPerformance incentives\nFlexible teaching schedule\nProfessional development workshops\nPaid time off for religious holidays\nTransportation allowance',
      employmentType: 'Part-time',
      mbtiTypes: 'ENFJ,ESFJ,ENFP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    // New job postings across Malaysian states with diverse professions
    {
      title: 'Software Engineer',
      company: 'Tech Innovations Sdn Bhd',
      location: 'Kuala Lumpur',
      salary: 'RM 5,000 - RM 8,000',
      description: 'Develop and maintain web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions.',
      requirements: 'Bachelor\'s degree in Computer Science or related field. Proficiency in JavaScript, React, and Node.js. 2+ years of experience in software development.',
      responsibilities: 'Design and implement new features for web applications\nWrite clean, maintainable, and efficient code\nTroubleshoot and debug issues in existing systems\nCollaborate with UI/UX designers to implement responsive designs\nParticipate in code reviews and provide constructive feedback\nStay updated with emerging trends and technologies',
      benefits: 'Competitive salary package\nPerformance bonuses\nComprehensive health insurance\nProfessional certification sponsorship\nFlexible working hours\nRemote work opportunities\nStocked pantry and meal allowances',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,INTP,ENTP,ENTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Graphic Designer',
      company: 'Creative Vision Studios',
      location: 'Penang',
      salary: 'RM 3,000 - RM 5,000',
      description: 'Create visual concepts for marketing materials, websites, and social media. Develop design elements that inspire, inform, and captivate audiences.',
      requirements: 'Diploma or Degree in Graphic Design. Proficiency in Adobe Creative Suite. Strong portfolio demonstrating creativity and technical skills.',
      responsibilities: 'Create engaging visual content for digital and print media\nDevelop brand identity elements including logos and style guides\nProduce illustrations, infographics, and other visual assets\nEnsure design consistency across all platforms\nCollaborate with marketing team on campaign materials\nStay current with design trends and techniques',
      benefits: 'Healthcare coverage\nCreative workspace environment\nProfessional design tool subscriptions\nFlexible working hours\nSkill development workshops\nPortfolio development opportunities',
      employmentType: 'Full-time',
      mbtiTypes: 'ISFP,INFP,ENFP,ENTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Electrical Technician',
      company: 'PowerGrid Solutions',
      location: 'Johor',
      salary: 'RM 2,800 - RM 4,000',
      description: 'Install, maintain, and repair electrical systems in commercial and industrial settings. Troubleshoot electrical issues and ensure compliance with safety regulations.',
      requirements: 'Certificate in Electrical Engineering. Valid electrical license. 3+ years of experience in electrical maintenance.',
      responsibilities: 'Install and maintain electrical systems and equipment\nTroubleshoot electrical malfunctions and repair defects\nRead and interpret electrical schematics and blueprints\nEnsure compliance with safety codes and regulations\nPerform preventive maintenance on electrical systems\nDocument all maintenance activities and repairs',
      benefits: 'Overtime compensation\nSafety equipment provided\nHealthcare insurance\nTransportation allowance\nTechnical skills training\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTP,ISTJ,ESTP,ESTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Marketing Manager',
      company: 'Global Brands Malaysia',
      location: 'Selangor',
      salary: 'RM 6,000 - RM 9,000',
      description: 'Develop and implement marketing strategies to promote products and services. Analyze market trends and competitor activities to identify new opportunities.',
      requirements: 'Bachelor\'s degree in Marketing or Business. 5+ years of experience in marketing roles. Strong understanding of digital marketing channels.',
      responsibilities: 'Develop and execute comprehensive marketing strategies\nManage marketing budget and optimize campaign ROI\nLead market research initiatives to identify customer needs\nCoordinate with advertising agencies and creative teams\nAnalyze campaign performance metrics\nMonitor competitive landscape and industry trends',
      benefits: 'Performance-based bonuses\nComprehensive medical coverage\nProfessional development fund\nRetirement savings plan\nFlexible working arrangements\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFJ,ENTJ,ENTP,ESFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Human Resources Specialist',
      company: 'Talent Solutions HR',
      location: 'Kuala Lumpur',
      salary: 'RM 4,500 - RM 6,500',
      description: 'Manage recruitment processes, employee relations, and HR policies. Provide support to employees and management on HR-related matters.',
      requirements: 'Bachelor\'s degree in Human Resources or related field. Knowledge of Malaysian employment laws. Strong interpersonal skills.',
      responsibilities: 'Coordinate recruitment and onboarding processes\nManage employee benefits administration\nImplement and update HR policies and procedures\nHandle employee relations issues and concerns\nMaintain accurate HR records and documentation\nConduct training sessions on HR-related topics',
      benefits: 'Medical and dental insurance\nProfessional certification support\nPaid time off\nFlexible working hours\nEmployee wellness programs\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFJ,ESFJ,ISFJ,INFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Civil Engineer',
      company: 'BuildTech Engineering',
      location: 'Sabah',
      salary: 'RM 4,500 - RM 7,000',
      description: 'Design and oversee construction projects including roads, buildings, and water systems. Ensure projects meet specifications and comply with regulations.',
      requirements: 'Bachelor\'s degree in Civil Engineering. Professional engineer certification. Experience with AutoCAD and other engineering software.',
      responsibilities: 'Prepare detailed engineering designs and specifications\nDevelop project timelines and cost estimates\nOversee construction activities to ensure quality standards\nCoordinate with contractors and stakeholders\nConduct site inspections and quality control\nEnsure compliance with safety and building regulations',
      benefits: 'Project completion bonuses\nProfessional liability insurance\nTraining and certification support\nPaid annual leave\nHealth insurance coverage\nRelocation assistance',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTJ,ISTP,INTJ,ESTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Hospitality Manager',
      company: 'Luxury Resort & Spa',
      location: 'Langkawi, Kedah',
      salary: 'RM 5,000 - RM 7,500',
      description: 'Oversee daily operations of the resort, ensuring exceptional guest experiences. Manage staff, budgets, and implement service improvement initiatives.',
      requirements: 'Degree in Hospitality Management or related field. 5+ years of experience in luxury hospitality. Strong leadership and problem-solving skills.',
      responsibilities: 'Manage day-to-day operations of the resort\nRecruit, train, and supervise hospitality staff\nImplement service standards and procedures\nHandle guest feedback and resolve complaints\nMonitor budget and control expenses\nDevelop marketing strategies to increase occupancy',
      benefits: 'Complimentary stays at partner properties\nService charge sharing\nMeals during shifts\nTransportation allowance\nHealthcare coverage\nPerformance bonuses\nStaff accommodation options',
      employmentType: 'Full-time',
      mbtiTypes: 'ESFJ,ENFJ,ESTJ,ENTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Environmental Scientist',
      company: 'EcoSustain Research',
      location: 'Sarawak',
      salary: 'RM 4,000 - RM 6,000',
      description: 'Conduct field studies and research on environmental issues affecting rainforests and wildlife. Develop conservation strategies and prepare detailed reports.',
      requirements: 'Master\'s degree in Environmental Science or related field. Experience with environmental impact assessments. Willingness to work in remote locations.',
      responsibilities: 'Design and implement environmental research projects\nConduct field sampling and data collection\nAnalyze environmental data and interpret findings\nPrepare detailed reports and research papers\nDevelop conservation and sustainability strategies\nCollaborate with government agencies and NGOs',
      benefits: 'Research funding opportunities\nField equipment allowance\nConference attendance sponsorship\nFlexible work schedule\nHealth insurance\nPaid fieldwork expenses\nProfessional development support',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,INTP,INFJ,ISTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Financial Analyst',
      company: 'Investment Partners Malaysia',
      location: 'Kuala Lumpur',
      salary: 'RM 5,500 - RM 8,500',
      description: 'Analyze financial data, prepare investment reports, and provide recommendations to clients. Monitor market trends and identify investment opportunities.',
      requirements: 'Bachelor\'s degree in Finance, Accounting, or Economics. CFA certification preferred. Strong analytical and quantitative skills.',
      responsibilities: 'Analyze financial statements and market trends\nDevelop financial models and forecasts\nPrepare detailed investment reports\nEvaluate investment opportunities and risks\nPresent findings to clients and stakeholders\nMonitor portfolio performance and make recommendations',
      benefits: 'Performance-based bonuses\nCFA exam fee reimbursement\nComprehensive health insurance\nRetirement savings plan\nProfessional development allowance\nPaid financial software subscriptions',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTJ,INTJ,ESTJ,ENTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Primary School Teacher',
      company: 'International School of Excellence',
      location: 'Melaka',
      salary: 'RM 3,200 - RM 4,800',
      description: 'Teach core subjects to primary school students using creative and engaging teaching methods. Develop lesson plans and assess student progress.',
      requirements: 'Bachelor\'s degree in Education. Teaching certification. Experience working with children of different backgrounds and abilities.',
      responsibilities: 'Develop and implement engaging lesson plans\nTeach core subjects including mathematics, science, and language arts\nAssess student progress and provide constructive feedback\nMaintain classroom discipline and positive learning environment\nCommunicate regularly with parents about student progress\nParticipate in school events and extracurricular activities',
      benefits: 'School holidays off\nSubsidized continuing education\nHealthcare benefits\nClassroom supplies allowance\nProfessional development workshops\nOpportunities for career advancement',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFJ,ESFJ,INFJ,ISFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Mechanical Engineer',
      company: 'Precision Manufacturing Sdn Bhd',
      location: 'Penang',
      salary: 'RM 4,500 - RM 7,000',
      description: 'Design mechanical components and systems for manufacturing processes. Conduct testing and implement improvements to increase efficiency and quality.',
      requirements: 'Bachelor\'s degree in Mechanical Engineering. Proficiency in CAD software. Experience in product design and development.',
      responsibilities: 'Design mechanical components and systems using CAD software\nDevelop technical specifications and documentation\nConduct product testing and performance analysis\nTroubleshoot and resolve engineering issues\nCollaborate with cross-functional teams\nImplement process improvements to enhance efficiency',
      benefits: 'Performance bonuses\nProfessional certification support\nHealthcare coverage\nRetirement savings plan\nRelocation assistance\nFlexible working hours',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTP,INTP,ESTJ,ENTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Chef de Cuisine',
      company: 'Fusion Gastronomy Restaurant',
      location: 'Kuala Lumpur',
      salary: 'RM 6,000 - RM 9,000',
      description: 'Lead kitchen operations, develop innovative menus, and maintain food quality standards. Train and supervise kitchen staff while managing costs.',
      requirements: 'Culinary arts degree or equivalent experience. 7+ years in upscale restaurant kitchens. Strong leadership and creativity.',
      responsibilities: 'Develop innovative menus and recipes\nManage kitchen operations and staff\nEnsure food quality and presentation standards\nControl food costs and inventory\nTrain and mentor junior chefs\nMaintain kitchen hygiene and safety standards',
      benefits: 'Performance bonuses\nMeal allowance\nHealthcare coverage\nCulinary training opportunities\nPaid annual leave\nStaff accommodation options',
      employmentType: 'Full-time',
      mbtiTypes: 'ISFP,ESFP,ISTP,ESTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Agricultural Scientist',
      company: 'Sustainable Farming Institute',
      location: 'Perak',
      salary: 'RM 4,000 - RM 6,000',
      description: 'Research and develop improved farming techniques suitable for Malaysian climate and soil conditions. Provide consultation to local farmers on sustainable practices.',
      requirements: 'Master\'s degree in Agricultural Science or related field. Knowledge of tropical agriculture. Experience with crop analysis and soil science.',
      responsibilities: 'Conduct research on crop improvement and sustainable farming\nDevelop and test new agricultural techniques\nAnalyze soil samples and crop performance data\nProvide training and consultation to local farmers\nPrepare research papers and technical reports\nCollaborate with government agencies on agricultural policies',
      benefits: 'Research funding opportunities\nConference attendance sponsorship\nFieldwork allowance\nHealthcare coverage\nHousing subsidy in rural areas\nFlexible work arrangements',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTJ,ISFJ,INTJ,INTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Cybersecurity Analyst',
      company: 'Digital Defense Solutions',
      location: 'Selangor',
      salary: 'RM 5,000 - RM 8,000',
      description: 'Monitor and protect organizational IT systems from cyber threats. Implement security measures and respond to security incidents.',
      requirements: 'Bachelor\'s degree in Computer Science or related field. Cybersecurity certifications (CISSP, CEH). Experience with security tools and protocols.',
      responsibilities: 'Monitor networks for security breaches and investigate incidents\nImplement and maintain security systems and protocols\nPerform vulnerability assessments and penetration testing\nDevelop security policies and procedures\nProvide security awareness training to staff\nStay updated on emerging threats and countermeasures',
      benefits: 'Certification fee reimbursement\nContinuing education allowance\nHealthcare coverage\nPerformance bonuses\nFlexible working hours\nRemote work options\nProfessional conference attendance',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,ISTJ,INTP,ISTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Nursing Supervisor',
      company: 'Community Healthcare Center',
      location: 'Negeri Sembilan',
      salary: 'RM 5,000 - RM 7,000',
      description: 'Oversee nursing staff, ensure quality patient care, and implement healthcare protocols. Coordinate with doctors and other healthcare professionals.',
      requirements: 'Bachelor\'s degree in Nursing. Registered nurse license. 5+ years of clinical experience. Leadership skills.',
      responsibilities: 'Supervise nursing staff and coordinate patient care activities\nDevelop and implement nursing care plans\nEnsure compliance with healthcare regulations and protocols\nManage medical supplies and equipment inventory\nProvide direct patient care as needed\nMentor and train new nursing staff',
      benefits: 'Healthcare coverage for family\nContinuing education support\nShift differentials\nRetirement plan\nProfessional liability insurance\nUniform allowance',
      employmentType: 'Full-time',
      mbtiTypes: 'ESFJ,ISFJ,ENFJ,INFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Content Creator',
      company: 'Digital Media Productions',
      location: 'Kuala Lumpur',
      salary: 'RM 3,500 - RM 5,500',
      description: 'Create engaging content for various digital platforms including social media, websites, and video channels. Develop creative strategies to increase audience engagement.',
      requirements: 'Degree in Communications, Media, or related field. Portfolio demonstrating content creation skills. Knowledge of SEO and social media algorithms.',
      responsibilities: 'Create engaging content for various digital platforms\nDevelop creative strategies to increase audience engagement\nCollaborate with marketing team on campaign materials\nStay updated with social media trends and algorithms',
      benefits: 'Healthcare coverage\nCreative workspace environment\nProfessional development workshops\nPortfolio development opportunities\nOpportunities for career advancement',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFP,ENTP,INFP,ISFP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Petroleum Engineer',
      company: 'Malaysian Energy Corporation',
      location: 'Terengganu',
      salary: 'RM 7,000 - RM 12,000',
      description: 'Design and implement methods for extracting oil and gas from deposits below the earth\'s surface. Develop plans for drilling operations and production.',
      requirements: 'Bachelor\'s degree in Petroleum Engineering. Experience with drilling procedures and reservoir analysis. Knowledge of safety regulations.',
      responsibilities: 'Design and implement methods for extracting oil and gas\nConduct drilling operations and monitor reservoir performance\nAnalyze drilling data and optimize well performance\nDevelop and implement safety protocols\nPrepare detailed reports and presentations',
      benefits: 'Competitive salary package\nProfessional certification support\nHealthcare coverage\nRetirement savings plan\nRelocation assistance\nTravel opportunities',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,ENTJ,ISTJ,ESTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Tourism Officer',
      company: 'Malaysia Tourism Development',
      location: 'Pahang',
      salary: 'RM 3,500 - RM 5,000',
      description: 'Promote local tourist destinations and develop tourism programs. Collaborate with stakeholders to enhance visitor experiences and increase tourism revenue.',
      requirements: 'Degree in Tourism Management or Hospitality. Knowledge of Malaysian culture and heritage. Strong communication and marketing skills.',
      responsibilities: 'Promote local tourist destinations and develop tourism programs\nCollaborate with stakeholders to enhance visitor experiences\nCoordinate marketing campaigns and events\nMonitor tourism trends and market dynamics',
      benefits: 'Healthcare coverage\nProfessional development opportunities\nRetirement savings plan\nFlexible working hours\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'ESFP,ENFP,ESFJ,ENFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Logistics Coordinator',
      company: 'Global Supply Chain Solutions',
      location: 'Johor',
      salary: 'RM 3,800 - RM 5,500',
      description: 'Coordinate transportation, warehousing, and distribution operations. Optimize supply chain processes and ensure timely delivery of goods.',
      requirements: 'Degree in Logistics, Supply Chain Management, or Business. Experience with logistics software and inventory management. Strong organizational skills.',
      responsibilities: 'Coordinate transportation, warehousing, and distribution operations\nOptimize supply chain processes and ensure timely delivery\nManage inventory and stock levels\nTroubleshoot logistics issues and implement solutions',
      benefits: 'Healthcare coverage\nTransportation allowance\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTJ,ESTJ,ISTP,ESTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Architectural Designer',
      company: 'Urban Vision Architects',
      location: 'Kuala Lumpur',
      salary: 'RM 4,500 - RM 7,500',
      description: 'Create architectural designs for residential and commercial projects. Prepare detailed drawings and work with clients to translate their vision into reality.',
      requirements: 'Bachelor\'s degree in Architecture. Proficiency in AutoCAD and 3D modeling software. Creative portfolio demonstrating design capabilities.',
      responsibilities: 'Create architectural designs for residential and commercial projects\nPrepare detailed drawings and work with clients\nTranslate their vision into reality\nEnsure design compliance with regulations and standards',
      benefits: 'Healthcare coverage\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'INFP,ISFP,INFJ,INTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Social Media Manager',
      company: 'Digital Engagement Agency',
      location: 'Penang',
      salary: 'RM 3,500 - RM 5,500',
      description: 'Develop and implement social media strategies for clients across various industries. Create content calendars and analyze performance metrics.',
      requirements: 'Degree in Marketing, Communications, or related field. Experience managing social media campaigns. Knowledge of analytics tools and content creation.',
      responsibilities: 'Develop and implement social media strategies\nCreate content calendars and analyze performance metrics\nCollaborate with marketing team on campaign materials\nStay updated with social media trends and algorithms',
      benefits: 'Healthcare coverage\nProfessional development workshops\nPortfolio development opportunities\nRetirement savings plan\nFlexible working hours\nTravel opportunities',
      employmentType: 'Full-time',
      mbtiTypes: 'ENFP,ESFP,ENTP,ENFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Aquaculture Technician',
      company: 'Sustainable Seafood Farms',
      location: 'Sabah',
      salary: 'RM 2,800 - RM 4,200',
      description: 'Monitor and maintain fish farming operations. Ensure optimal water quality, feeding schedules, and growth conditions for aquatic species.',
      requirements: 'Certificate or Diploma in Aquaculture or Marine Biology. Experience with water quality testing and fish health management. Physical stamina for fieldwork.',
      responsibilities: 'Monitor and maintain fish farming operations\nEnsure optimal water quality, feeding schedules, and growth conditions\nConduct water quality testing and fish health assessments\nImplement and maintain fish farming protocols',
      benefits: 'Healthcare coverage\nTransportation allowance\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTP,ISFP,ESTP,ISTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Customer Service Manager',
      company: 'Consumer Solutions Center',
      location: 'Selangor',
      salary: 'RM 4,200 - RM 6,000',
      description: 'Lead customer service team to resolve customer inquiries and complaints. Implement strategies to improve customer satisfaction and loyalty.',
      requirements: 'Bachelor\'s degree in Business or related field. 3+ years in customer service roles. Strong leadership and problem-solving abilities.',
      responsibilities: 'Lead customer service team to resolve inquiries and complaints\nImplement strategies to improve customer satisfaction and loyalty\nManage customer relationship management systems\nConduct customer satisfaction surveys and analyze results',
      benefits: 'Healthcare coverage\nProfessional certification support\nPaid time off\nFlexible working hours\nEmployee wellness programs\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ESFJ,ENFJ,ESTJ,ISFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Biotechnology Researcher',
      company: 'BioInnovation Labs',
      location: 'Perlis',
      salary: 'RM 4,500 - RM 7,000',
      description: 'Conduct research in biotechnology applications for agriculture and healthcare. Develop new methodologies and technologies through laboratory experimentation.',
      requirements: 'PhD or Master\'s degree in Biotechnology or related field. Experience with laboratory techniques and research methodologies. Publications in scientific journals preferred.',
      responsibilities: 'Conduct research in biotechnology applications\nDevelop new methodologies and technologies\nConduct laboratory experiments and analyze results\nPrepare research papers and presentations\nCollaborate with other researchers and scientists',
      benefits: 'Research funding opportunities\nProfessional certification support\nHealthcare coverage\nRetirement savings plan\nFlexible working hours\nTravel opportunities',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,INTP,INFJ,ISTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Event Planner',
      company: 'Spectacular Events Management',
      location: 'Kuala Lumpur',
      salary: 'RM 3,800 - RM 6,000',
      description: 'Plan and coordinate various events including corporate functions, weddings, and conferences. Manage vendors, budgets, and logistical details.',
      requirements: 'Degree in Event Management, Hospitality, or related field. Experience coordinating multiple events simultaneously. Strong attention to detail and problem-solving skills.',
      responsibilities: 'Plan and coordinate various events\nManage vendors, budgets, and logistical details\nEnsure event compliance with regulations and standards\nTroubleshoot event-related issues and implement solutions',
      benefits: 'Healthcare coverage\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'ESFJ,ENFJ,ESTJ,ESFP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Renewable Energy Specialist',
      company: 'Green Power Innovations',
      location: 'Sarawak',
      salary: 'RM 5,000 - RM 8,000',
      description: 'Develop and implement renewable energy projects such as solar and hydroelectric power. Conduct feasibility studies and manage project implementation.',
      requirements: 'Bachelor\'s degree in Engineering, Environmental Science, or related field. Knowledge of renewable energy technologies. Project management experience.',
      responsibilities: 'Develop and implement renewable energy projects\nConduct feasibility studies and manage project implementation\nAnalyze project feasibility and economic viability\nCoordinate with stakeholders and government agencies',
      benefits: 'Healthcare coverage\nTransportation allowance\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nTravel opportunities',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,ENTJ,INTP,ENTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Physiotherapist',
      company: 'Active Recovery Healthcare',
      location: 'Kelantan',
      salary: 'RM 3,800 - RM 5,500',
      description: 'Provide physiotherapy services to patients recovering from injuries or managing chronic conditions. Develop and implement personalized treatment plans.',
      requirements: 'Bachelor\'s degree in Physiotherapy. Licensed with the Malaysian Physiotherapy Association. Experience in clinical settings and patient care.',
      responsibilities: 'Provide physiotherapy services to patients\nDevelop and implement personalized treatment plans\nConduct assessments and develop treatment programs\nMonitor patient progress and adjust treatment plans',
      benefits: 'Healthcare coverage\nProfessional certification support\nPaid time off\nFlexible working hours\nEmployee wellness programs\nPerformance bonuses',
      employmentType: 'Full-time',
      mbtiTypes: 'ISFJ,ESFJ,ISFP,INFJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Data Scientist',
      company: 'Analytics Insight Corp',
      location: 'Kuala Lumpur',
      salary: 'RM 6,000 - RM 10,000',
      description: 'Analyze complex datasets to extract valuable business insights. Develop predictive models and machine learning algorithms to solve business problems.',
      requirements: 'Master\'s degree in Data Science, Statistics, or related field. Proficiency in Python, R, and SQL. Experience with machine learning techniques and data visualization.',
      responsibilities: 'Analyze complex datasets to extract valuable business insights\nDevelop predictive models and machine learning algorithms\nConduct data analysis and visualization\nImplement data-driven decision-making strategies\nCollaborate with cross-functional teams',
      benefits: 'Healthcare coverage\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'INTJ,INTP,ENTJ,ENTP',
      deadline: generateFutureDate(),
      adminId: admin.id,
    },
    {
      title: 'Halal Certification Specialist',
      company: 'Global Halal Authority',
      location: 'Labuan',
      salary: 'RM 4,000 - RM 6,000',
      description: 'Inspect and audit facilities seeking halal certification. Ensure compliance with halal standards and prepare detailed reports on findings.',
      requirements: 'Degree in Food Science, Islamic Studies, or related field. Knowledge of halal requirements and certification processes. Attention to detail and integrity.',
      responsibilities: 'Inspect and audit facilities seeking halal certification\nEnsure compliance with halal standards\nPrepare detailed reports on findings\nConduct training sessions on halal certification requirements',
      benefits: 'Healthcare coverage\nProfessional certification support\nRetirement savings plan\nFlexible working hours\nTravel opportunities\nCorporate wellness program',
      employmentType: 'Full-time',
      mbtiTypes: 'ISTJ,ISFJ,ESTJ,ENTJ',
      deadline: generateFutureDate(),
      adminId: admin.id,
    }
  ];

  for (const job of jobPostings) {
    await prisma.jobPosting.create({
      data: job,
    });
  }

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  }); 